#
# Banana-Pi-R2 kernel and uboot 
#
# Copyright (c) GW Delight Technologies Co., Ltd, 2017-2017
#
# Authors:
#  Dong Liu <beyond2002@gmail.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

language: c

compiler:
  - gcc

sudo: required
dist: trusty

# Remove bogus python installations from PATH,
# see https://github.com/travis-ci/travis-ci/issues/5326
before_install:
  - export PATH=$(echo $PATH | sed 's/\/opt\/python[^:]*//g')
# For fold
  - export -f travis_nanoseconds
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish

install:
  # Install additional packages
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu xenial main'
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-mako gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu make u-boot-tools

script:
  - echo 'test webgl-stub' && echo -en 'travis_fold:start:build\\r'
  - ./autobuild.sh
  - echo -en 'travis_fold:end:build\\r'

addons:
  coverity_scan:
    project:
      name: "beyond2002/BPI-R2-bsp"
    notification_email: beyond2002@gmail.com
    build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/ci/coverity-scan-build.sh
    build_command_prepend: "cov-configure --comptype gcc --compiler arm-linux-gnueabihf-gcc --template; cov-configure --comptype gcc --compiler aarch64-linux-gnu-gcc --template"
    build_command: "unused"
    branch_pattern: coverity_scan.*

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Dong Liu"
      - git config --local user.email "beyond2002@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
      provider: releases
      api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
      file: 
        - "./SD/4.4.70-BPI-R2-Kernel.tgz"
        - "./SD/4.4.70-BPI-R2-Kernel-net.tgz"
        - "./SD/BOOTLOADER-bpi-r2.tgz"
        - "./SD/BPI-BOOT-bpi-r2.tgz"
        - "./SD/BPI-BOOT/bananapi/bpi-r2/linux/uImage"
        - "./SD/BPI-BOOT/bananapi/bpi-r2/linux/uEnv.txt"
        - "./linux-mt/arch/arm/boot/dts/mt7623n-bpi-r2.dtb"
      skip_cleanup: true

